<?php
/*
 * (C) 2016-2018 Emanuel Gafton, NOT/ING.
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version. See LICENSE.md.
 */

// For OS X
$PYTHON_PATH = '/opt/local/bin/python';
$APP_PATH    = '/Users/egafton/Sites/visplot/html5';

// For Linux
//$PYTHON_PATH = '/usr/bin/python';
//$APP_PATH    = '/var/www/html/visplot';
