// eslint.config.js
// Run: npx eslint .
export default [
  {
    ignores: [
      "visplot/js/aladin.min.js",
      "visplot/js/leaflet-openweathermap.js",
      "visplot/js/moment-timezone-with-data.min.js",
      "visplot/js/jsplitter.js"
    ],
    files: ["visplot/js/*.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: {
        $: "readonly",
        config: "readonly",
        sla: "readonly",
        helper: "readonly",
        driver: "readonly",
        Driver: "readonly",
        Graph: "readonly",
        SkyGraph: "readonly",
        TargetList: "readonly",
        Target: "readonly",
        Night: "readonly",
        serializer: "readonly",
        window: "readonly",
        moment: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        setTimeout: "readonly",
        localStorage: "readonly",
        console: "readonly",
        document: "readonly",
        Blob: "readonly",
        Option: "readonly",
        Image: "readonly",
        JSZip: "readonly",
        CodeMirror: "readonly"
      },
    },
    rules: {
      "no-unused-vars": "error",
      "no-undef": "error",
      "for-direction": "error",
      "getter-return": "error",
      "no-class-assign": "error",
      "no-compare-neg-zero": "error",
      "no-cond-assign": "error",
      "no-const-assign": "error",
      "no-constant-condition": "error",
      "no-constant-binary-expression": "error",
      "no-constructor-return": "error",
      "no-dupe-args": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-func-assign": "error",
      "no-self-assign": "error",
      "no-setter-return": "error",
      "no-unexpected-multiline": "error",
      "no-unreachable": "error",
      "no-unsafe-finally": "error",
      "no-unsafe-negation": "error",
      "no-useless-assignment": "error",
      "no-sparse-arrays": "error",
      "no-obj-calls": "error",
      "use-isnan": "error",
      "eqeqeq": "error",
      "no-eq-null": "error",
      "no-extra-semi": "error",
      "semi": ["error", "always"],
      "semi-spacing": "error",
      "block-spacing": "error",
      "indent": ["error", 4],
      "comma-spacing": "error",
      "no-trailing-spaces": "error",
      "no-multi-spaces": "error",
      "no-multiple-empty-lines": "error",
      "no-tabs": "error",
      "object-curly-newline": "error",
      "spaced-comment": "error",
      "keyword-spacing": "error",
      "eol-last": "error",
      "comma-dangle": "error",
      "camelcase": "error",
      "yoda": ["error", "never"],
      "func-name-matching": "error",
      "func-names": ["error", "never"],
      "no-array-constructor": "error",
      "no-useless-catch": "error",
      "no-redeclare": "error",
      "no-invalid-this": "error",
      "no-global-assign": "error",
      "no-extra-boolean-cast": "error",
      "no-empty": "error",
      "no-empty-static-block": "error",
      "no-case-declarations": "error",
      "no-else-return": "error",
      "no-undefined": "error",
      "no-unneeded-ternary": "error",
      "no-unused-expressions": "error",
      "no-shadow": "error",
      "curly": "error"
    },
  },
];
